package com.vioverlord.java17trainer;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Typeface;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
  String lang="zh"; ArrayList<Q> bank=new ArrayList<>(), run=new ArrayList<>(); int idx=0, ok=0, chosenStage=0; long endAt=0; LinearLayout root;
  String[] stZh={"基础声明与变量","类型转换与字符串","流程控制","数组与集合","方法与构造器","继承与多态","异常与常用API"};
  String[] stJa={"基本宣言と変数","型変換と文字列","制御構文","配列とコレクション","メソッドとコンストラクタ","継承とポリモーフィズム","例外と基本API"};
  public void onCreate(Bundle b){super.onCreate(b); lang=getPreferences(0).getString("lang","zh"); buildBank(); home();}
  TextView tv(String s,int sp,int style){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTypeface(Typeface.DEFAULT,style);v.setPadding(8,8,8,8);root.addView(v);return v;}
  Button btn(String s){Button b=new Button(this);b.setText(s);root.addView(b);return b;}
  void page(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,28);sv.addView(root);setContentView(sv);} 
  String L(String z,String j){return "ja".equals(lang)?j:z;} String stageName(int i){return "ja".equals(lang)?stJa[i]:stZh[i];} String c(String... lines){StringBuilder b=new StringBuilder();for(String x:lines){if(b.length()>0)b.append('\n');b.append(x);}return b.toString();}
  void home(){page();tv("Java Silver 17 Trainer",26,Typeface.BOLD);tv(L(bank.size()+"道精修模拟题｜重点是理解，不是背题",bank.size()+"問の精選模擬問題｜暗記ではなく理解重視"),15,0);tv(L("当前阶段：","現在のステージ：")+stageName(chosenStage),16,Typeface.BOLD);btn(L("切换中文/日本語","中文/日本語 切替")).setOnClickListener(v->{lang="zh".equals(lang)?"ja":"zh";getPreferences(0).edit().putString("lang",lang).apply();home();});btn(L("选择大纲阶段","ステージ選択")).setOnClickListener(v->pickStage());btn(L("按当前大纲练习","現在ステージで練習")).setOnClickListener(v->start(0,chosenStage));btn(L("当前大纲随机 20题","現在ステージからランダム 20問")).setOnClickListener(v->start(1,chosenStage));btn(L("全范围随机 30题","全範囲ランダム 30問")).setOnClickListener(v->start(2,-1));btn(L("正式模拟考试 80题 / 180分钟","本番模擬試験 80問 / 180分")).setOnClickListener(v->start(3,-1));btn(L("Java关键字中日查询","Javaキーワード中日検索")).setOnClickListener(v->keywords());btn(L("成绩与弱项统计","成績と弱点分析")).setOnClickListener(v->stats());}
  void pickStage(){new AlertDialog.Builder(this).setItems("ja".equals(lang)?stJa:stZh,(d,which)->{chosenStage=which;home();}).show();}
  void start(int mode,int stage){run.clear();for(Q q:bank)if(stage<0||q.stage==stage)run.add(q);if(mode!=0)Collections.shuffle(run);int limit=mode==0?run.size():mode==1?20:mode==2?30:80;while(run.size()>limit)run.remove(run.size()-1);idx=0;ok=0;endAt=mode==3?System.currentTimeMillis()+180L*60L*1000L:0;showQ();}
  void showQ(){if(idx>=run.size()){finishRun();return;}page();Q q=run.get(idx);tv(L("第 ","第 ")+(idx+1)+" / "+run.size()+"    "+L("正确：","正解：")+ok,16,Typeface.BOLD);if(endAt>0)tv(L("剩余约：","残り約：")+Math.max(0,(endAt-System.currentTimeMillis())/60000)+L(" 分钟"," 分"),14,0);tv("["+stageName(q.stage)+"]  "+q.type+" / Lv"+q.diff+" / "+q.tag,13,0);tv(q.text(),18,Typeface.BOLD);ArrayList<CheckBox> boxes=new ArrayList<>();for(int i=0;i<q.optsZ.length;i++){CheckBox cb=new CheckBox(this);cb.setText((char)('A'+i)+". "+q.opt(i));cb.setTextSize(16);final CheckBox me=cb;if(q.single)cb.setOnClickListener(v->{if(me.isChecked())for(CheckBox x:boxes)if(x!=me)x.setChecked(false);});boxes.add(cb);root.addView(cb);}Button sub=btn(L("提交并查看讲解","提出して解説を見る"));btn(L("返回主页","ホームへ戻る")).setOnClickListener(v->home());sub.setOnClickListener(v->{HashSet<Integer> s=new HashSet<>();for(int i=0;i<boxes.size();i++)if(boxes.get(i).isChecked())s.add(i);boolean good=s.equals(q.ans);if(good)ok++;mark(q,good);for(CheckBox c:boxes)c.setEnabled(false);sub.setEnabled(false);tv(good?L("正确","正解"):L("错误","不正解"),20,Typeface.BOLD);tv(L("正确答案：","正解：")+q.answerText(),16,Typeface.BOLD);tv(q.exp(),16,0);btn(idx+1>=run.size()?L("查看本轮结果","今回の結果を見る"):L("下一题","次の問題")).setOnClickListener(n->{idx++;showQ();});});}
  void finishRun(){page();tv(L("本轮完成","今回終了"),26,Typeface.BOLD);int total=run.size();tv(L("得分：","スコア：")+ok+" / "+total+"  "+(total==0?0:ok*100/total)+"%",22,Typeface.BOLD);tv(L("分布：","分布："),18,Typeface.BOLD);HashMap<String,Integer> m=new HashMap<>();for(Q q:run)m.put(stageName(q.stage),m.containsKey(stageName(q.stage))?m.get(stageName(q.stage))+1:1);for(String k:m.keySet())tv(k+"  "+m.get(k)+L("题","問"),15,0);btn(L("回主页","ホームへ")).setOnClickListener(v->home());}
  void stats(){page();SharedPreferences p=getPreferences(0);int t=p.getInt("allT",0),cc=p.getInt("allC",0);tv(L("累计成绩","累計成績"),25,Typeface.BOLD);tv(L("总正确率：","総合正答率：")+cc+" / "+t+"  "+(t==0?0:cc*100/t)+"%",20,Typeface.BOLD);for(int i=0;i<7;i++){int tt=p.getInt("s"+i+"T",0),c=p.getInt("s"+i+"C",0);tv(stageName(i)+"  "+c+"/"+tt+"  "+(tt==0?0:c*100/tt)+"%",15,0);}btn(L("回主页","ホームへ")).setOnClickListener(v->home());}
  void mark(Q q,boolean good){SharedPreferences.Editor e=getPreferences(0).edit();inc(e,"allT");if(good)inc(e,"allC");inc(e,"s"+q.stage+"T");if(good)inc(e,"s"+q.stage+"C");e.apply();} void inc(SharedPreferences.Editor e,String k){SharedPreferences p=getPreferences(0);e.putInt(k,p.getInt(k,0)+1);} 
  void keywords(){page();tv(L("Java关键字中日查询","Javaキーワード中日検索"),24,Typeface.BOLD);String[][] ks={{"class","类声明","クラス宣言"},{"interface","接口","インターフェース"},{"extends","继承父类","親クラスを継承"},{"implements","实现接口","インターフェースを実装"},{"static","属于类本身","クラス自体に属する"},{"final","不可再赋值/继承/重写","再代入・継承・オーバーライド不可"},{"abstract","抽象","抽象"},{"var","局部变量类型推断","ローカル変数型推論"},{"record","不可变数据载体","不変データキャリア"},{"yield","switch表达式返回值","switch式の値を返す"}};for(String[] k:ks)tv(k[0]+" : "+L(k[1],k[2]),15,0);btn(L("回主页","ホームへ")).setOnClickListener(v->home());}
  void buildBank(){if(!bank.isEmpty())return;
    a(0,"EXECUTION",3,"local-variable",c("下面代码的结果是？", "class Main {", "  public static void main(String[] args) {", "    int x;", "    if (args.length == 0) x = 10;", "    System.out.println(x);", "  }", "}"),c("次のコードの結果は？", "class Main {", "  public static void main(String[] args) {", "    int x;", "    if (args.length == 0) x = 10;", "    System.out.println(x);", "  }", "}"),o("10","0","null","编译错误"),o("10","0","null","コンパイルエラー"),3,"局部变量必须在所有可能路径上明确赋值。args.length 不一定为 0，因此 x 可能未初始化。","ローカル変数はすべての可能な経路で明示的に代入されている必要がある。args.length が0とは限らないため x は未初期化の可能性がある。");
    a(0,"EXECUTION",2,"numeric-promotion",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  byte b = 3;", "  b = b + 2;", "  System.out.println(b);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  byte b = 3;", "  b = b + 2;", "  System.out.println(b);", "}}"),o("5","3","编译错误","运行时异常"),o("5","3","コンパイルエラー","実行時例外"),2,"b + 2 会提升为 int，不能不强转赋回 byte。","b + 2 は int に昇格するため、キャストなしで byte に代入できない。");
    a(0,"EXECUTION",2,"compound-assignment",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  byte b = 3;", "  b += 2;", "  System.out.println(b);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  byte b = 3;", "  b += 2;", "  System.out.println(b);", "}}"),o("5","3","编译错误","运行时异常"),o("5","3","コンパイルエラー","実行時例外"),0,"复合赋值包含隐式强制转换，b += 2 可以编译。","複合代入には暗黙のキャストが含まれるため b += 2 はコンパイル可能。");
    a(0,"SINGLE",2,"var",c("哪一行可以编译？", "A. var a;", "B. var b = null;", "C. var c = 10;", "D. var d = {1,2,3};"),c("コンパイルできる行はどれか。", "A. var a;", "B. var b = null;", "C. var c = 10;", "D. var d = {1,2,3};"),o("A","B","C","D"),o("A","B","C","D"),2,"var 只能用于有初始化表达式的局部变量，不能单独声明、不能用 null 推断、不能直接接数组初始化器。","var は初期化式のあるローカル変数だけに使える。単独宣言、null推論、配列初期化子のみは不可。");
    a(0,"EXECUTION",3,"scope",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  for (int i = 0; i < 2; i++) { }", "  System.out.println(i);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  for (int i = 0; i < 2; i++) { }", "  System.out.println(i);", "}}"),o("0","1","2","编译错误"),o("0","1","2","コンパイルエラー"),3,"for 初始化部分声明的 i 作用域只在 for 语句内。","for の初期化部で宣言した i のスコープは for 文の中だけ。");
    a(0,"MULTIPLE",3,"literal",c("选择所有可以编译的声明。"),c("コンパイルできる宣言をすべて選べ。"),o("long a = 10;","float b = 10.0;","double c = 10.0f;","char d = 65;"),o("long a = 10;","float b = 10.0;","double c = 10.0f;","char d = 65;"),new int[]{0,2,3},"10 可扩大到 long；10.0 是 double，不能直接给 float；float 可扩大到 double；65 是 char 可表示范围内的 int 常量。","10 は long に拡大可能。10.0 は double なので float へ直接代入不可。float は double へ拡大可能。65 は char の範囲内の int 定数。");
    a(1,"EXECUTION",3,"string-equality",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  String a = \"Ja\" + \"va\";", "  String b = new String(\"Java\");", "  System.out.println(a == b);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  String a = \"Ja\" + \"va\";", "  String b = new String(\"Java\");", "  System.out.println(a == b);", "}}"),o("true","false","Java","编译错误"),o("true","false","Java","コンパイルエラー"),1,"a 指向字符串池中的对象，new String 会创建新对象，== 比较引用。","a は文字列プール、new String は新しいオブジェクト。== は参照比較。");
    a(1,"EXECUTION",3,"stringbuilder",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  StringBuilder sb = new StringBuilder(\"abc\");", "  String s = sb.append(\"d\").substring(1,3);", "  System.out.println(sb + \":\" + s);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  StringBuilder sb = new StringBuilder(\"abc\");", "  String s = sb.append(\"d\").substring(1,3);", "  System.out.println(sb + \":\" + s);", "}}"),o("abcd:bc","abc:bc","abcd:bcd","编译错误"),o("abcd:bc","abc:bc","abcd:bcd","コンパイルエラー"),0,"append 会修改 StringBuilder；substring(1,3) 取索引 1 到 2。","append は StringBuilder を変更する。substring(1,3) はインデックス1から2まで。");
    a(1,"EXECUTION",2,"wrapper-cache",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  Integer a = 127;", "  Integer b = 127;", "  Integer c = 128;", "  Integer d = 128;", "  System.out.println((a == b) + \" \" + (c == d));", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  Integer a = 127;", "  Integer b = 127;", "  Integer c = 128;", "  Integer d = 128;", "  System.out.println((a == b) + \" \" + (c == d));", "}}"),o("true true","true false","false true","false false"),o("true true","true false","false true","false false"),1,"Integer 自动装箱通常缓存 -128 到 127。128 不保证同一引用。","Integer の自動ボクシングは通常 -128 から127をキャッシュする。128は同一参照とは限らない。");
    a(1,"SINGLE",2,"text-block",c("关于文本块 text block，正确的是？"),c("テキストブロックについて正しい説明は？"),o("用三个双引号开始和结束","只能保存一行文本","Java 17 不支持文本块","文本块类型不是 String"),o("3つのダブルクォートで開始・終了する","1行だけ保存できる","Java 17では非対応","型はStringではない"),0,"文本块是 String 字面量的一种，使用三重双引号。","テキストブロックは String リテラルの一種で、三重引用符を使う。");
    a(1,"EXECUTION",3,"operator",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  int x = 1;", "  System.out.println(x++ + ++x);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  int x = 1;", "  System.out.println(x++ + ++x);", "}}"),o("3","4","5","编译错误"),o("3","4","5","コンパイルエラー"),1,"x++ 使用旧值 1 后变 2；++x 先变 3 再使用；合计 4。","x++ は旧値1を使ってから2になる。++x は先に3になって使われる。合計4。");
    a(2,"EXECUTION",3,"switch-fallthrough",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  int x = 2;", "  switch (x) {", "    case 1: System.out.print(\"A\");", "    case 2: System.out.print(\"B\");", "    default: System.out.print(\"C\");", "  }", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  int x = 2;", "  switch (x) {", "    case 1: System.out.print(\"A\");", "    case 2: System.out.print(\"B\");", "    default: System.out.print(\"C\");", "  }", "}}"),o("B","BC","ABC","编译错误"),o("B","BC","ABC","コンパイルエラー"),1,"传统 switch 没有 break 会从匹配 case 继续向下执行。","従来switchは break がないと一致した case から下へ実行される。");
    a(2,"EXECUTION",3,"switch-expression",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  int n = 2;", "  String r = switch(n) {", "    case 1 -> \"one\";", "    case 2 -> \"two\";", "    default -> \"other\";", "  };", "  System.out.println(r);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  int n = 2;", "  String r = switch(n) {", "    case 1 -> \"one\";", "    case 2 -> \"two\";", "    default -> \"other\";", "  };", "  System.out.println(r);", "}}"),o("one","two","other","编译错误"),o("one","two","other","コンパイルエラー"),1,"switch 表达式可以产生值，箭头形式不会贯穿。","switch式は値を返せる。矢印形式ではフォールスルーしない。");
    a(2,"EXECUTION",3,"loop-control",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  int sum = 0;", "  for (int i = 0; i < 5; i++) {", "    if (i == 2) continue;", "    if (i == 4) break;", "    sum += i;", "  }", "  System.out.println(sum);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  int sum = 0;", "  for (int i = 0; i < 5; i++) {", "    if (i == 2) continue;", "    if (i == 4) break;", "    sum += i;", "  }", "  System.out.println(sum);", "}}"),o("3","4","6","10"),o("3","4","6","10"),1,"累加 0、1、3；i=2 跳过，i=4 退出，因此结果 4。","0,1,3 を加算する。i=2 はスキップ、i=4 は終了なので4。");
    a(2,"SINGLE",2,"switch-type",c("传统 switch 的选择表达式不能是哪一种？"),c("従来switchの選択式に使えない型はどれか。"),o("String","enum","long","char"),o("String","enum","long","char"),2,"传统 switch 不支持 long/float/double/boolean。","従来switchは long/float/double/boolean をサポートしない。");
    a(3,"EXECUTION",2,"array-default",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  String[] a = new String[2];", "  System.out.println(a[0].length());", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  String[] a = new String[2];", "  System.out.println(a[0].length());", "}}"),o("0","null","编译错误","NullPointerException"),o("0","null","コンパイルエラー","NullPointerException"),3,"引用类型数组元素默认是 null，对 null 调用方法会抛出 NullPointerException。","参照型配列の要素のデフォルトは null。null に対してメソッド呼び出しをすると NullPointerException。");
    a(3,"EXECUTION",3,"array-dimension",c("下面代码的结果是？", "class Main { public static void main(String[] args) {", "  int[][] a = new int[2][];", "  System.out.println(a[0][0]);", "}}"),c("次のコードの結果は？", "class Main { public static void main(String[] args) {", "  int[][] a = new int[2][];", "  System.out.println(a[0][0]);", "}}"),o("0","null","编译错误","NullPointerException"),o("0","null","コンパイルエラー","NullPointerException"),3,"a[0] 本身是 null，还没有指向 int[]，访问 a[0][0] 会空指针。","a[0] 自体が null で int[] を参照していないため、a[0][0] はNullPointerException。");
    a(3,"EXECUTION",3,"arraylist-remove",c("下面代码的结果是？", "import java.util.*;", "class Main { public static void main(String[] args) {", "  var list = new ArrayList<Integer>();", "  list.add(1); list.add(2); list.add(3);", "  list.remove(1);", "  System.out.println(list);", "}}"),c("次のコードの結果は？", "import java.util.*;", "class Main { public static void main(String[] args) {", "  var list = new ArrayList<Integer>();", "  list.add(1); list.add(2); list.add(3);", "  list.remove(1);", "  System.out.println(list);", "}}"),o("[1, 3]","[2, 3]","[1, 2]","运行时异常"),o("[1, 3]","[2, 3]","[1, 2]","実行時例外"),0,"remove(1) 在这里匹配 remove(int index)，删除索引 1 的元素 2。","remove(1) は remove(int index) に解決され、インデックス1の要素2を削除する。");
    a(3,"EXECUTION",3,"list-of",c("下面代码的结果是？", "import java.util.*;", "class Main { public static void main(String[] args) {", "  var list = List.of(\"A\", \"B\");", "  list.add(\"C\");", "  System.out.println(list.size());", "}}"),c("次のコードの結果は？", "import java.util.*;", "class Main { public static void main(String[] args) {", "  var list = List.of(\"A\", \"B\");", "  list.add(\"C\");", "  System.out.println(list.size());", "}}"),o("2","3","编译错误","UnsupportedOperationException"),o("2","3","コンパイルエラー","UnsupportedOperationException"),3,"List.of 返回不可变列表，add 会在运行时抛 UnsupportedOperationException。","List.of は変更不可リストを返す。add は実行時に UnsupportedOperationException。");
    a(3,"MULTIPLE",3,"collection",c("选择所有正确说法。"),c("正しい説明をすべて選べ。"),o("数组长度用 length 字段","String 长度用 length() 方法","ArrayList 元素个数用 size() 方法","数组长度可以运行时改变"),o("配列の長さは length フィールド","Stringの長さは length() メソッド","ArrayListの要素数は size() メソッド","配列の長さは実行時に変更できる"),new int[]{0,1,2},"数组长度固定；数组是 length 字段，不是方法。","配列長は固定。配列は length フィールドでありメソッドではない。");
    a(4,"EXECUTION",3,"overload",c("下面代码的结果是？", "class Main {", "  static void m(long x){ System.out.print(\"long\"); }", "  static void m(Integer x){ System.out.print(\"Integer\"); }", "  public static void main(String[] args){ m(10); }", "}"),c("次のコードの結果は？", "class Main {", "  static void m(long x){ System.out.print(\"long\"); }", "  static void m(Integer x){ System.out.print(\"Integer\"); }", "  public static void main(String[] args){ m(10); }", "}"),o("long","Integer","编译错误","运行时异常"),o("long","Integer","コンパイルエラー","実行時例外"),0,"重载优先级中，基本类型扩大优先于装箱，因此 int -> long。","オーバーロードでは基本型の拡大変換がボクシングより優先されるため int -> long。");
    a(4,"EXECUTION",3,"varargs",c("下面代码的结果是？", "class Main {", "  static void m(int x){ System.out.print(\"int\"); }", "  static void m(int... x){ System.out.print(\"varargs\"); }", "  public static void main(String[] args){ m(1); }", "}"),c("次のコードの結果は？", "class Main {", "  static void m(int x){ System.out.print(\"int\"); }", "  static void m(int... x){ System.out.print(\"varargs\"); }", "  public static void main(String[] args){ m(1); }", "}"),o("int","varargs","编译错误","运行时异常"),o("int","varargs","コンパイルエラー","実行時例外"),0,"固定参数方法优先于可变参数。","固定引数メソッドは可変長引数より優先される。");
    a(4,"EXECUTION",3,"constructor",c("下面代码的结果是？", "class A { A(){ System.out.print(\"A\"); } }", "class B extends A { B(){ System.out.print(\"B\"); } }", "class Main { public static void main(String[] args){ new B(); } }"),c("次のコードの結果は？", "class A { A(){ System.out.print(\"A\"); } }", "class B extends A { B(){ System.out.print(\"B\"); } }", "class Main { public static void main(String[] args){ new B(); } }"),o("A","B","AB","BA"),o("A","B","AB","BA"),2,"子类构造器会先隐式调用父类无参构造器，再执行自身构造器体。","サブクラスのコンストラクタは先に親の無引数コンストラクタを暗黙的に呼び、その後自身を実行する。");
    a(4,"EXECUTION",3,"constructor-this",c("下面代码是否能编译？", "class A {", "  A(){ System.out.print(\"A\"); }", "  A(int x){", "    System.out.print(x);", "    this();", "  }", "}"),c("次のコードはコンパイルできるか。", "class A {", "  A(){ System.out.print(\"A\"); }", "  A(int x){", "    System.out.print(x);", "    this();", "  }", "}"),o("可以，输出 1A","可以，输出 A1","编译错误","运行时异常"),o("可能、1Aを出力","可能、A1を出力","コンパイルエラー","実行時例外"),2,"this(...) 或 super(...) 如果出现，必须是构造器第一条语句。","this(...) または super(...) がある場合、コンストラクタの最初の文でなければならない。");
    a(4,"MULTIPLE",3,"method-signature",c("关于方法重载，选择所有正确说法。"),c("メソッドのオーバーロードについて正しいものをすべて選べ。"),o("只改变返回值不能构成重载","参数个数不同可以构成重载","参数顺序不同可以构成重载","只改变 throws 声明可以构成重载"),o("戻り値だけの変更では不可","引数の個数が違えば可能","引数の順序が違えば可能","throws宣言だけの変更で可能"),new int[]{0,1,2},"重载看方法名和参数列表；返回值、throws、访问修饰符不能单独决定重载。","オーバーロードはメソッド名と引数リストで決まる。戻り値、throws、アクセス修飾子だけでは不可。");
    a(5,"EXECUTION",3,"override",c("下面代码的结果是？", "class A { String name(){ return \"A\"; } }", "class B extends A { String name(){ return \"B\"; } }", "class Main { public static void main(String[] args){", "  A x = new B();", "  System.out.println(x.name());", "}}"),c("次のコードの結果は？", "class A { String name(){ return \"A\"; } }", "class B extends A { String name(){ return \"B\"; } }", "class Main { public static void main(String[] args){", "  A x = new B();", "  System.out.println(x.name());", "}}"),o("A","B","编译错误","运行时异常"),o("A","B","コンパイルエラー","実行時例外"),1,"实例方法调用运行时看实际对象类型，B 重写的方法被执行。","インスタンスメソッドは実行時の実体型で決まる。Bでオーバーライドされたメソッドが実行される。");
    a(5,"EXECUTION",3,"field-hiding",c("下面代码的结果是？", "class A { int v = 1; }", "class B extends A { int v = 2; }", "class Main { public static void main(String[] args){", "  A x = new B();", "  System.out.println(x.v);", "}}"),c("次のコードの結果は？", "class A { int v = 1; }", "class B extends A { int v = 2; }", "class Main { public static void main(String[] args){", "  A x = new B();", "  System.out.println(x.v);", "}}"),o("1","2","编译错误","运行时异常"),o("1","2","コンパイルエラー","実行時例外"),0,"字段没有多态，按引用变量的编译时类型 A 访问。","フィールドはポリモーフィズムの対象ではなく、参照変数のコンパイル時型 A でアクセスされる。");
    a(5,"EXECUTION",3,"static-hiding",c("下面代码的结果是？", "class A { static void m(){ System.out.print(\"A\"); } }", "class B extends A { static void m(){ System.out.print(\"B\"); } }", "class Main { public static void main(String[] args){", "  A x = new B();", "  x.m();", "}}"),c("次のコードの結果は？", "class A { static void m(){ System.out.print(\"A\"); } }", "class B extends A { static void m(){ System.out.print(\"B\"); } }", "class Main { public static void main(String[] args){", "  A x = new B();", "  x.m();", "}}"),o("A","B","编译错误","NullPointerException"),o("A","B","コンパイルエラー","NullPointerException"),0,"static 方法是隐藏不是重写，按引用变量编译时类型解析。","staticメソッドはオーバーライドではなく隠蔽。参照変数のコンパイル時型で解決される。");
    a(5,"SINGLE",3,"interface-default",c("下面代码的判断正确的是？", "interface A { default void m(){ } }", "interface B { default void m(){ } }", "class C implements A, B { }"),c("次のコードについて正しい説明は？", "interface A { default void m(){ } }", "interface B { default void m(){ } }", "class C implements A, B { }"),o("可以编译，继承 A 的 m","可以编译，继承 B 的 m","编译错误，必须解决默认方法冲突","运行时才决定调用哪个"),o("コンパイル可能、Aのmを継承","コンパイル可能、Bのmを継承","コンパイルエラー、defaultメソッド衝突を解決する必要がある","実行時に決まる"),2,"两个接口提供相同签名的 default 方法时，实现类必须重写解决冲突。","2つのインターフェースが同じシグネチャのdefaultメソッドを持つ場合、実装クラスは上書きして解決する必要がある。");
    a(5,"EXECUTION",3,"casting",c("下面代码的结果是？", "class A { }", "class B extends A { void b(){ System.out.print(\"B\"); } }", "class C extends A { }", "class Main { public static void main(String[] args){", "  A x = new C();", "  ((B)x).b();", "}}"),c("次のコードの結果は？", "class A { }", "class B extends A { void b(){ System.out.print(\"B\"); } }", "class C extends A { }", "class Main { public static void main(String[] args){", "  A x = new C();", "  ((B)x).b();", "}}"),o("B","编译错误","ClassCastException","NullPointerException"),o("B","コンパイルエラー","ClassCastException","NullPointerException"),2,"编译期 A 可能转成 B，因此能编译；运行时实际对象是 C，不是 B，抛 ClassCastException。","コンパイル時には A から B へのキャストは可能。しかし実体は C なので実行時に ClassCastException。");
    a(6,"SINGLE",3,"catch-order",c("下面代码是否能编译？", "try {", "  throw new java.io.IOException();", "} catch (Exception e) {", "} catch (java.io.IOException e) {", "}"),c("次のコードはコンパイルできるか。", "try {", "  throw new java.io.IOException();", "} catch (Exception e) {", "} catch (java.io.IOException e) {", "}"),o("可以，先执行 IOException catch","可以，先执行 Exception catch","编译错误，后面的 catch 不可达","运行时异常"),o("可能、IOException catch が先","可能、Exception catch が先","コンパイルエラー、後続catchが到達不能","実行時例外"),2,"父类 Exception 已经捕获 IOException，后面的 IOException catch 永远到达不了。","親クラス Exception が IOException を捕捉するため、後ろの IOException catch は到達不能。");
    a(6,"EXECUTION",3,"finally-return",c("下面代码的结果是？", "class Main {", "  static int test(){", "    try { return 1; }", "    finally { return 2; }", "  }", "  public static void main(String[] args){ System.out.println(test()); }", "}"),c("次のコードの結果は？", "class Main {", "  static int test(){", "    try { return 1; }", "    finally { return 2; }", "  }", "  public static void main(String[] args){ System.out.println(test()); }", "}"),o("1","2","编译错误","运行时异常"),o("1","2","コンパイルエラー","実行時例外"),1,"finally 中的 return 会覆盖 try 中准备返回的值。考试里这是危险写法，但语法允许。","finally 内の return は try の return 値を上書きする。危険な書き方だが構文上は可能。");
    a(6,"EXECUTION",3,"try-with-resources",c("下面代码的结果是？", "class R implements AutoCloseable {", "  String name; R(String n){name=n;}", "  public void close(){ System.out.print(name); }", "}", "class Main { public static void main(String[] args){", "  try(R a=new R(\"A\"); R b=new R(\"B\")){ System.out.print(\"T\"); }", "}}"),c("次のコードの結果は？", "class R implements AutoCloseable {", "  String name; R(String n){name=n;}", "  public void close(){ System.out.print(name); }", "}", "class Main { public static void main(String[] args){", "  try(R a=new R(\"A\"); R b=new R(\"B\")){ System.out.print(\"T\"); }", "}}"),o("TAB","TBA","ABT","BAT"),o("TAB","TBA","ABT","BAT"),1,"try-with-resources 资源关闭顺序与创建顺序相反，所以先 B 后 A。","try-with-resources のリソースは作成順と逆順で閉じられるため、B が先で A が後。");
    a(6,"SINGLE",2,"checked-exception",c("哪个异常通常属于 checked exception？"),c("通常 checked exception に分類されるものはどれか。"),o("RuntimeException","NullPointerException","java.io.IOException","ArithmeticException"),o("RuntimeException","NullPointerException","java.io.IOException","ArithmeticException"),2,"IOException 是受检异常，需要捕获或声明；RuntimeException 及其子类是非受检异常。","IOException はチェック例外で、捕捉または宣言が必要。RuntimeException配下は非チェック例外。");
    a(6,"EXECUTION",2,"record",c("下面代码的结果是？", "record User(String name, int age) { }", "class Main { public static void main(String[] args){", "  var u = new User(\"Tom\", 20);", "  System.out.println(u.name() + \"-\" + u.age());", "}}"),c("次のコードの結果は？", "record User(String name, int age) { }", "class Main { public static void main(String[] args){", "  var u = new User(\"Tom\", 20);", "  System.out.println(u.name() + \"-\" + u.age());", "}}"),o("Tom-20","User-Tom","编译错误","运行时异常"),o("Tom-20","User-Tom","コンパイルエラー","実行時例外"),0,"record 会自动生成与组件同名的访问器 name() 和 age()。","record はコンポーネント名と同じアクセサ name() と age() を自動生成する。");
  }
  String[] o(String a,String b,String c,String d){return new String[]{a,b,c,d};}
  void a(int s,String type,int diff,String tag,String z,String j,String[] oz,String[] oj,int ans,String ez,String ej){a(s,type,diff,tag,z,j,oz,oj,new int[]{ans},ez,ej);} 
  void a(int s,String type,int diff,String tag,String z,String j,String[] oz,String[] oj,int[] ans,String ez,String ej){bank.add(new Q(s,type,diff,tag,z,j,oz,oj,ans,ez,ej));}
  class Q{int stage,diff;String type,tag,z,j,ez,ej;String[] optsZ,optsJ;HashSet<Integer> ans=new HashSet<>();boolean single;Q(int s,String t,int d,String g,String z,String j,String[] oz,String[] oj,int[] a,String ez,String ej){stage=s;type=t;diff=d;tag=g;this.z=z;this.j=j;optsZ=oz;optsJ=oj;for(int x:a)ans.add(x);single=a.length==1;this.ez=ez;this.ej=ej;}String text(){return L(z,j);}String opt(int i){return "ja".equals(lang)?optsJ[i]:optsZ[i];}String exp(){return L(ez,ej);}String answerText(){StringBuilder b=new StringBuilder();for(int i:ans){if(b.length()>0)b.append(", ");b.append((char)('A'+i));}return b.toString();}}
}
